# -*- coding: utf-8 -*-
"""InHerEraAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16bM3dtXHOw5WASby0eFww04QOsKEPpFL

# **Introduction**

In the beauty and cosmetics industry, it's not uncommon to see advertisements targeting females to make them feel like they need to fix their looks with their products. Time and time again, we see new products and proceedures hit the market with the promise of making women look beautiful, but often this has the opposite effect, leading to more women not feeling good about themselves or their appearance.

"In Her Era" is an organization looking to further examine the effects of the beauty industry, specifically how that affects different demographics of women. They currently wish to start a "Beauty Therapy" service, a one-on-one virtual consultation service meant to inspire women to embrace their own natural beauty. The group wants to further understand how they should communicate with their audience, regarding what platforms to use and what demographics are more likely to have a want to change their appearance. On top of that, they want to also assess what could be potential causes of their insecurities according to certain demographics' plights.

I along with the help of the "In Her Era" team assembled a survey to assess common problems and desires of those afflicted by certain kinds of body insecurity. For the scope of this analysis, I am going to be comparing the proportions of which age, sexual orientation, and political alignment.

The main responses to questions I will be looking at are "Do you wish to change your appearance," and "Of the following online services, I am most likely to join ___."

# **Characteristics of Data and Survey**

All of the questions of the survey, excluding demographic questions and questions regarding open responses/critiques of the survey, had three answers available for selection: Yes, No, or I don't know. The following statistics were collected from Google Forms:

Of the 193 respondants to this survey, 165 (85%) identified as female and 23 (12%) identified as Male, but we will only be looking at the female respondants of the survey.

Over 95% of respondants were from the United States, with the 3 most likely states of origin being Utah (68.3%), California (9.8%), and Washington (3.8%).

The most common race was White (73.1%), with the next most common being Asian (9.8%) and Hispanic/Latino (8.8%).

All responses related to age were collected as age brackets, and those from 15-24 years old were the most respondant to the survey (88.6%). The 11.6% of the survey were 25 years old and older.

60.6% of respondants identified as heterosexual while 33.1% of respondants identified as gay, lesbian, or bisexual, the majority of which identified as bisexual. Only 3 respondants identified as transgender. For the sake of analysis, I'm going to be lumping lesbian, gay, and bisexual respondants as "queer."

Of the poltical alignments available, the majority of the data identified politically as liberal or moderately liberal (53.3%). The next most popular response was the total between centrist and independent, making up a total of 29% of the survey data. the remaining 17.6% of the data identified as conservative or moderately conservative. For the sake of analysis, I've lumped these into three categories according to the alignments listed.

# **Cleaning Data**

Because I had control of how data was entered into the system, I was able to cleam my data in Google Forms beforehand. This was accomplished by me making all the questions I was looking to answer concretely required before any submissions to the dataset. There is the moderately unknown factor of the "I don't know" answer in a lot of the questions present, but I feel that it would be a misrepresentation of the data to not include it. Indecision can be a telling answer just as much as decisiveness can be.

# **Sorting Data**
"""

# importing all needed libraries and assigning my survey to a dataframe variable #

import pandas as pd
import string
import matplotlib
import matplotlib.pyplot as plt
path = "/content/drive/MyDrive/Assignment Data/In Her Era Survey Analysis/In Her Era Survey (Responses).csv"
df = pd.read_csv(path)

# Sorting data into gender and data categories #

#gender
df_women = df[df["Gender"] == "Female"]

#age
df_youngw = df_women[df_women["Age"] == ("15-24 years old")]
df_oldw = df_women[df_women["Age"] != ("15-24 years old")]

#sexuality
df_queer = df_women[df_women['Sexuality'].isin(['Gay','Lesbian','Bisexual'])]

df_straight = df_women[df_women['Sexuality'].isin(['Straight/Heterosexual'])]

#politics
df_liberal = df_women[df_women['Politics'].isin(['Moderate Liberal','Liberal'])]
df_conservative = df_women[df_women['Politics'].isin(['Moderate Conservative', 'Conservative'])]
df_independent = df_women[df_women['Politics'].isin(['Independent','Centrist'])]

#correlation dataframe

#this function returns the proportion of how much a given answer is in a series.  the proportion is presented as an integer, which will be useful for comparison because direct comparison of quantity rather than proportion
# would mispresent certain data.

def CountProportion (series, answer):
  total = 0
  ansTotal = 0
  for i in series:
    total = total+1
    if i == answer:
      ansTotal = ansTotal+1
    else:
      continue
  try:
    proportion = (ansTotal/total)*100
  except ZeroDivisionError:
    proportion = 0
  return int(proportion)

# returns a series that can quanitify "Yes" and "No" answers. "I don't know" is answer considered between Yes and No given the function.
def BinarySeries (series):
  newSeries = []
  for i in series:
    if i == "Yes":
      newSeries.append(1)
    elif i == "No":
      newSeries.append(0)
    else:
      newSeries.append(0.5)
  return newSeries

"""# **Results for Young Women**

Problems that young women have in proportions:
"""

# sorting young women data into a usable pie chart to display the percentage of each possible response. #

dfBeautyStandard = df_youngw.groupby('Fit Beauty Standard')['Fit Beauty Standard'].count().sort_values()
dfBeautyStandard.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Young Women on if They Fit the Beauty Standard in Their Country")

# sorting young women data into a usable pie chart to display the percentage of each possible response. #

dfChangeAppearance = df_youngw.groupby("Change Appearance")['Change Appearance'].count().sort_values()
dfChangeAppearance.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Proportion of Young Women that Wish to Change their Appearance")

# sorting young women data into a usable pie chart to display the percentage of each possible response. #

dfTrustInfluencers = df_youngw.groupby('Influencer Trust')['Influencer Trust'].count().sort_values()
dfTrustInfluencers.plot(kind="pie",autopct='%1.1f%%', title="Proportion of Young Women that Trust Beauty Influencers", ylabel="")

# sorting young women data into a usable pie chart to display the percentage of each possible response. #

dfTrustBrands = df_youngw.groupby('Brand Trust')['Brand Trust'].count().sort_values()
dfTrustBrands.plot(kind="pie",autopct='%1.1f%%', ylabel="", title='Proportion of Young Women that Trust Beauty Brands')

# sorting young women data into a usable pie chart to display the percentage of each possible response #

dfOverwhelm = df_youngw.groupby('Overwhelm in Stores')['Overwhelm in Stores'].count().sort_values()
dfOverwhelm.plot(kind="pie",autopct='%1.1f%%', ylabel="", title='Proportion of Young Women that are Overwhelmed by Beauty Stores')

dfTherapy = df_youngw.groupby('Therapy')['Therapy'].count().sort_values()
dfTherapy.plot(kind="pie",autopct='%1.1f%%', ylabel="", title='Proportion of Young Women that Approve of Therapy')

dfVif = df_youngw.groupby('Value in Features')['Value in Features'].count().sort_values()
dfVif.plot(kind="pie",autopct='%1.1f%%', ylabel="", title='Proportion of Young Women that See Value in All their Features')

"""# **Results for Comparison of Age**"""

youngwProp = CountProportion(df_youngw['Change Appearance'], "Yes")
oldwProp = CountProportion(df_oldw['Change Appearance'], "Yes")
Labels = ["ages 15-24", "ages 25+"]
plt.bar(Labels, [youngwProp, oldwProp])
plt.title('Proportion of Women that Wish to Change their Appearance (Age)')
plt.show()

youngwProp

oldwProp

"""As you can see, 69% of younger women in the study wish they could change their appearance compared to only 50% of women 25 and older. This could potentially be because younger women are on social media more often and exposed to more beauty related content. to test this, I decided to test the correlation coefficient of saying yes to consuming beauty content on social media and wanting to change their appearance."""

changeAp = BinarySeries(df_women['Change Appearance'])
beautyCo = BinarySeries(df_women['Consume Beauty'])
data = {"Change Appearance": changeAp,
  "Beauty Content": beautyCo}
dataframe = pd.DataFrame(data)

print(dataframe.corr())

"""Because the correlation coefficnt is a low .26, the variables have a weak correlation at best, even if thewy're correlated at all. However, .26 is not negligable. With further testing, there could potentially be something to be said about social media exposure and desire to change appearance, but that's a topic for another study."""

df_youngwFilt = df_youngw.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_youngwFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Young Women's Online Service Preference")

df_oldwFilt = df_oldw.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_oldwFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Women Over 25's Online Service Preference")

"""Young Women generally had a better spread of online service use, with most major services (excluding Slack) getting roughly 25% of the vote, but Discord comes out by a slight margin as the winner (38.). However, slightly over half of the women over 25 years old would prefer their a Facebook Group as their service of choice.

# **Results for Comparison in Sexual Orientation**
"""

straightProp = CountProportion(df_straight['Change Appearance'], "Yes")
queerProp = CountProportion(df_queer['Change Appearance'], "Yes")
Labels = ["Straight Women", "Queer Women"]
plt.bar(Labels, [straightProp, queerProp])
plt.title('Proportion of Women that Wish to Change their Appearance (Sexuality)')
plt.show()

straightProp

queerProp

"""By a similar striking margin, 15% more queer women said Yes to wanting to change their appearance. Based on the assumption that most marketing is done for a straight audience, perhaps queer women feel as if they don't fit the same beauty standard that straight women do. I decided to test that hypothesis via correlation."""

changeAp = BinarySeries(df_women['Change Appearance'])
beautySt = BinarySeries(df_women['Fit Beauty Standard'])
data = {"Change Appearance": changeAp,
  "Fit Beauty Standard": beautySt}
dataframe = pd.DataFrame(data)

print(dataframe.corr())

"""There is only a slight -.11 correlation between the two variables, which suggests that the desire to change appearance isn't necessarily because they don't feel like they feel they don't fit the beauty standard. Because this correlation is so weak, it can be discarded."""

df_straightFilt = df_straight.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_straightFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Straight Women's Online Service Preference")

df_queerFilt = df_queer.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_queerFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Queer Women's Online Service Preference")

"""# **Results for Comparison in Political Alignment**"""

libProp = CountProportion(df_liberal['Change Appearance'], "Yes")
consProp = CountProportion(df_conservative['Change Appearance'], "Yes")
indepProp = CountProportion(df_independent['Change Appearance'], "Yes")
Labels = ["Liberal Women", "Conservative Women", "Independent Women"]
plt.bar(Labels, [libProp, consProp, indepProp])
plt.title('Proportion of Women that Wish to Change their Appearance (Politics)')
plt.show()

libProp

consProp

indepProp

"""In a striking display, only half of conservative women believe have a desire to change their appearance. Independent Women have a staggering 77% want to change their appearance followed closely by liberal with 69%. As a general assumption, most conservative women have great roots in their heritage, whether that be racial or religious. Perhaps racial heritage and the desire to change appearance are correlated variables."""

changeAp = BinarySeries(df_women['Change Appearance'])
racialHer = BinarySeries(df_women['Race Importance'])
data = {"Change Appearance": changeAp,
  "Race Importance": racialHer}
dataframe = pd.DataFrame(data)

print(dataframe.corr())

"""The least correlated of all with only a -.09, racial heritage seems to have the least to do with desire to change appearance of all the variables studied thus far."""

df_liberalFilt = df_liberal.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_liberalFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Liberal Women's Online Service Preference")

df_conservativeFilt = df_conservative.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_conservativeFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Conservative Women's Online Service Preference")

df_independentFilt = df_independent.groupby('Online Services')['Online Services'].count().sort_values().tail(5)
df_independentFilt.plot(kind="pie",autopct='%1.1f%%', ylabel="", title="Independent Women's Online Service Preference")

"""Liberal Women use the highest variety of online services, with a pretty even spread between Facebook, Discord, and Reddit, with Discord taking the cake. A clear winner is present in the conservative category and that's Facebook. Independent Women have a similar spread to liberals, but favors Facebook more than it favors Discord by a margin of 2%.

# **Correlated Variables for Women's Desire to Change their Appearance**

To further understand which variables are most involved in the desire to change appearance and to further gear content towards things that might be useful to the respondants of this study, I set up a program that would tell me which variables were most correlated and which were least correlated. This was calculated by finding each variable's correlation coefficient with the variable "Change Appearance," the variable that represents the data on which women had a desire to change their appearance.

The closer a correlation coefficient is to 1 or -1, the more likely these variables are correlated. If something is positively correlated, it means the correlated answer is "Yes." If negatively correlated, the correlated answer is "No." Guide to what each correlation coefficient means:


*   -0.3 --- 0.3: weak to no correlation
*   -0.5 --- 0.5: mild correlation
*   -0.75 --- 0.75: strong correlation
*   -1 --- 1: indisputable correlation
"""

#program that calculated a datafram's correlation coefficient with

def CorrToChangeAp(dataframe):
  for column in dataframe:
    newSeries = BinarySeries(dataframe[column])
    changeAp = BinarySeries(dataframe['Change Appearance'])
    data = {'Change Appearance': changeAp,
             column: newSeries}
    df = pd.DataFrame(data)
    corr = df.corr()
    iloc = str(corr.iloc[1,0])
    print(column+": "+ iloc+"\t")

CorrToChangeAp(df_women)

"""No variable had a particularly strong correlation with a female respondant's desire to change her appearance, but there were a few that were weakly correlated. Here are the top correlations:

*   Social Media Influence: 0.341
*   Value in Features: -0.303
*   Consume Beauty: 0.260
*   25% Paycheck: 0.218

From these data, we can interpret that women who responded "Yes" to wanting to change their appearance:


*   Responded "Yes" most frequently to the question asking if social media influences their opinion.
*   Responded "No" slightly less frequently to the question asking if they valued their physical features.
*   Responded "Yes" decently frequently to the question asking if they consume beauty-related content on social media.
*   Responded "Yes" also decently frequently to the question asking them if they spent at least 25% of their paycheck on beauty products.

Unfortunately, none of these correlations are strong enough to make a definitive conclusion, but the correlation is significant enough to mentioned and considered.

# **Conclusion**

Younger women are more likely to want to change their appearance than older women. This could potentially be because of social media exposure, but the correlation is weak enough and the question asked in the survey leave this answer unconclusive.

Women who spend more on beauty products, are influenced by social media about their appearance, consume beauty content on social media, and who didn't value their features were slightly more likely to say that they want to change their appearance.

In order of use, the preferred online services for younger women are:

Discord (34.6%)

Facebook (27.9%)

Reddit (25%)

Slack (9%)

In order of use, the preferred online services for older women are:

Facebook (54.5%)

Reddit (18.2%)

Discord (9.1%)

Slack (4.5%)

Queer women are slightly more likely to want to change their appearance than straight women. There is a slight correlation between feeling like you don't fit beauty standards and wanting to change your appearance, but this correlation is nothing substantial.

In order of use, the preferred online services for straight women are:

Facebook (37.4%)

Discord (24.2%)

Reddit (21.2%)

Slack (8.1%)


In order of use, the preferred online services for queer women are:

Discord (42.3%)

Reddit (28.8%)

Facebook (23.1%)

Slack (1.9%)

Independent Women and Liberal Women were far and away more likely to want to change their appearance than Conservative women. Racial Importance is definitely not correlated to this fact, and this variable needs further examination.

In order of use, the preferred online services for liberal women are:

Discord (34.9%)

Facebook (27.9%)

Reddit (24.4%)

Slack (4.7%)


In order of use, the preferred online services for conservative women are:

Facebook (41.4%)

Reddit (20.7%)

Discord (20.7%)

Slack (6.9%)

In order of use, the preferred online services for independent women are:

Facebook (32.6%)

Discord (30.2%)

Reddit (25.6%)

Slack (7.0%)
"""